# Generated by Django 3.1.1 on 2020-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_text', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
            ],
        ),
    ]
