# Generated by Django 3.1.1 on 2020-09-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten_url_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='short_url_text',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
